# Generated by Django 5.0.7 on 2024-08-04 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cosmeticrole',
            name='color',
            field=models.CharField(default='white', max_length=100),
            preserve_default=False,
        ),
    ]
