# Generated by Django 5.0.7 on 2024-11-05 16:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_accountcosmeticroles_account_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='cosmeticrole',
            name='color',
            field=models.CharField(max_length=100, verbose_name='color'),
        ),
        migrations.AlterField(
            model_name='cosmeticrole',
            name='name',
            field=models.CharField(max_length=200, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='usercosmeticroles',
            name='cosmetic_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.cosmeticrole', verbose_name='cosmetic_role'),
        ),
        migrations.AlterField(
            model_name='usercosmeticroles',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.CharField(choices=[('en', 'English'), ('es', 'Español')], default='es', max_length=30)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
