# Generated by Django 5.0.7 on 2024-08-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0003_alter_brand_name_alter_car_brand_alter_car_car_model_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='image',
            field=models.ImageField(null=True, upload_to='brand_images/'),
        ),
    ]
