# Generated by Django 5.0.7 on 2024-08-09 20:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0007_remove_car_account_remove_comment_account_car_seller_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='brand',
        ),
    ]
