# Generated by Django 5.0.7 on 2024-08-10 23:38

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0008_remove_car_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='userboughtcars',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
